"""empty message

Revision ID: 0af8a50ad042
Revises: e1bc74cde696
Create Date: 2019-04-10 16:20:29.242877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0af8a50ad042'
down_revision = 'e1bc74cde696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyline_membership',
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_contributor', sa.Boolean(), nullable=True),
    sa.Column('is_visitor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('storyline_id', 'member_id')
    )
    op.drop_table('storyline_memebership')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyline_memebership',
    sa.Column('storyline_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_contributor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_visitor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], name='storyline_memebership_ibfk_1'),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], name='storyline_memebership_ibfk_2'),
    sa.PrimaryKeyConstraint('storyline_id', 'member_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('storyline_membership')
    # ### end Alembic commands ###
