"""empty message

Revision ID: 0e3602e9c281
Revises: 64118f353ed5
Create Date: 2019-04-19 20:59:53.517073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3602e9c281'
down_revision = '64118f353ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyline', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('storyline', sa.Column('start_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_storyline_end_date'), 'storyline', ['end_date'], unique=True)
    op.create_index(op.f('ix_storyline_start_date'), 'storyline', ['start_date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storyline_start_date'), table_name='storyline')
    op.drop_index(op.f('ix_storyline_end_date'), table_name='storyline')
    op.drop_column('storyline', 'start_date')
    op.drop_column('storyline', 'end_date')
    # ### end Alembic commands ###
