"""empty message

Revision ID: 146495384f0a
Revises: 9b92c67ad973
Create Date: 2019-04-06 13:10:54.329893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146495384f0a'
down_revision = '9b92c67ad973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('story_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'story', ['story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'story_id')
    # ### end Alembic commands ###
