"""empty message

Revision ID: 167fc66ffdfa
Revises: 0af8a50ad042
Create Date: 2019-04-11 16:36:18.641560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167fc66ffdfa'
down_revision = '0af8a50ad042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyline', sa.Column('slug', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_storyline_slug'), 'storyline', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storyline_slug'), table_name='storyline')
    op.drop_column('storyline', 'slug')
    # ### end Alembic commands ###
