"""empty message

Revision ID: 1762daf1f40f
Revises: 9079d910b3f5
Create Date: 2019-03-12 10:22:15.138404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1762daf1f40f'
down_revision = '9079d910b3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('geo_point_ibfk_1', 'geo_point', type_='foreignkey')
    op.drop_constraint('geo_point_ibfk_2', 'geo_point', type_='foreignkey')
    op.drop_column('geo_point', 'itinerary_end_id')
    op.drop_column('geo_point', 'itinerary_start_id')
    op.add_column('itinerary', sa.Column('end_point_id', sa.Integer(), nullable=True))
    op.add_column('itinerary', sa.Column('start_point_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'itinerary', 'geo_point', ['start_point_id'], ['id'])
    op.create_foreign_key(None, 'itinerary', 'geo_point', ['end_point_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itinerary', type_='foreignkey')
    op.drop_constraint(None, 'itinerary', type_='foreignkey')
    op.drop_column('itinerary', 'start_point_id')
    op.drop_column('itinerary', 'end_point_id')
    op.add_column('geo_point', sa.Column('itinerary_start_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('geo_point', sa.Column('itinerary_end_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('geo_point_ibfk_2', 'geo_point', 'itinerary', ['itinerary_start_id'], ['id'])
    op.create_foreign_key('geo_point_ibfk_1', 'geo_point', 'itinerary', ['itinerary_end_id'], ['id'])
    # ### end Alembic commands ###
