"""empty message

Revision ID: 197860721a90
Revises: 0d599d58baf7
Create Date: 2019-03-25 14:07:34.497303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '197860721a90'
down_revision = '0d599d58baf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('itinerary_ibfk_2', 'itinerary', type_='foreignkey')
    op.drop_constraint('itinerary_ibfk_1', 'itinerary', type_='foreignkey')
    op.drop_column('itinerary', 'start_point_id')
    op.drop_column('itinerary', 'end_point_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary', sa.Column('end_point_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('itinerary', sa.Column('start_point_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('itinerary_ibfk_1', 'itinerary', 'geo_point', ['start_point_id'], ['id'])
    op.create_foreign_key('itinerary_ibfk_2', 'itinerary', 'geo_point', ['end_point_id'], ['id'])
    # ### end Alembic commands ###
