"""empty message

Revision ID: 2ee276ca6d0f
Revises: c10cc917ed53
Create Date: 2019-04-01 09:37:03.671971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee276ca6d0f'
down_revision = 'c10cc917ed53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('request_file_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'request_file_name')
    # ### end Alembic commands ###
