"""markdown

Revision ID: 432585f064a8
Revises: 1415edf7d137
Create Date: 2018-09-02 10:20:10.180421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432585f064a8'
down_revision = '1415edf7d137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('html_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'html_content')
    # ### end Alembic commands ###
