"""empty message

Revision ID: 591d18f794d0
Revises: b275dedfbe2e
Create Date: 2019-04-03 09:06:49.802940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591d18f794d0'
down_revision = 'b275dedfbe2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('comment', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'comment')
    # ### end Alembic commands ###
