"""empty message

Revision ID: 64118f353ed5
Revises: 905bc145cd7e
Create Date: 2019-04-17 15:03:07.081869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64118f353ed5'
down_revision = '905bc145cd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('resized_url', sa.String(length=1400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'resized_url')
    # ### end Alembic commands ###
