"""empty message

Revision ID: 67ada03db79b
Revises: 8b28bea8ab05
Create Date: 2019-04-01 09:13:53.168026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ada03db79b'
down_revision = '8b28bea8ab05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_info', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'file_info')
    # ### end Alembic commands ###
