"""empty message

Revision ID: 8b28bea8ab05
Revises: b8f4cae72c15
Create Date: 2019-03-29 11:05:27.666289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b28bea8ab05'
down_revision = 'b8f4cae72c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('geo_point_ibfk_1', 'geo_point', type_='foreignkey')
    op.drop_column('geo_point', 'story_id')
    op.add_column('story', sa.Column('stay_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'story', 'geo_point', ['stay_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_column('story', 'stay_id')
    op.add_column('geo_point', sa.Column('story_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('geo_point_ibfk_1', 'geo_point', 'story', ['story_id'], ['id'])
    # ### end Alembic commands ###
