"""empty message

Revision ID: 8c1279214849
Revises: f2c848251ff2
Create Date: 2019-03-12 09:32:55.416148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1279214849'
down_revision = 'f2c848251ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_point', sa.Column('formatted_address', sa.String(length=140), nullable=True))
    op.add_column('geo_point', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('geo_point', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('geo_point', sa.Column('place', sa.String(length=32), nullable=True))
    op.add_column('itinerary', sa.Column('end_point', sa.Integer(), nullable=True))
    op.add_column('itinerary', sa.Column('starting_point', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'itinerary', 'geo_point', ['starting_point'], ['id'])
    op.create_foreign_key(None, 'itinerary', 'geo_point', ['end_point'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itinerary', type_='foreignkey')
    op.drop_constraint(None, 'itinerary', type_='foreignkey')
    op.drop_column('itinerary', 'starting_point')
    op.drop_column('itinerary', 'end_point')
    op.drop_column('geo_point', 'place')
    op.drop_column('geo_point', 'longitude')
    op.drop_column('geo_point', 'latitude')
    op.drop_column('geo_point', 'formatted_address')
    # ### end Alembic commands ###
