"""empty message

Revision ID: 905bc145cd7e
Revises: 167fc66ffdfa
Create Date: 2019-04-16 16:24:00.415244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905bc145cd7e'
down_revision = '167fc66ffdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('feature', sa.Enum('NONE', 'FEATURED', 'SECOND', 'THIRD', name='imagefeature'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'feature')
    # ### end Alembic commands ###
