"""empty message

Revision ID: 9282bfc18391
Revises: 13bb7a797f36
Create Date: 2019-03-25 14:58:44.571915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9282bfc18391'
down_revision = '13bb7a797f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary', sa.Column('end_point_id', sa.Integer(), nullable=True))
    op.add_column('itinerary', sa.Column('start_point_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'itinerary', 'geo_point', ['end_point_id'], ['id'])
    op.create_foreign_key(None, 'itinerary', 'geo_point', ['start_point_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itinerary', type_='foreignkey')
    op.drop_constraint(None, 'itinerary', type_='foreignkey')
    op.drop_column('itinerary', 'start_point_id')
    op.drop_column('itinerary', 'end_point_id')
    # ### end Alembic commands ###
