"""empty message

Revision ID: 9b92c67ad973
Revises: ffaed584810d
Create Date: 2019-04-06 13:02:02.234110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b92c67ad973'
down_revision = 'ffaed584810d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('story', sa.Column('friend_id', sa.Integer(), nullable=True))
    op.add_column('story', sa.Column('stay_description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'story', 'user', ['friend_id'], ['id'])
    op.add_column('user', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'media', ['picture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'picture_id')
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_column('story', 'stay_description')
    op.drop_column('story', 'friend_id')
    op.drop_table('comment')
    # ### end Alembic commands ###
