"""empty message

Revision ID: b275dedfbe2e
Revises: 2ee276ca6d0f
Create Date: 2019-04-01 21:13:41.796305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b275dedfbe2e'
down_revision = '2ee276ca6d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('exif_height', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('exif_width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'exif_width')
    op.drop_column('media', 'exif_height')
    # ### end Alembic commands ###
