"""empty message

Revision ID: b73cc8494ef6
Revises: 1762daf1f40f
Create Date: 2019-03-25 11:03:27.299186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73cc8494ef6'
down_revision = '1762daf1f40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_point', sa.Column('story_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'geo_point', 'story', ['story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'geo_point', type_='foreignkey')
    op.drop_column('geo_point', 'story_id')
    # ### end Alembic commands ###
