"""empty message

Revision ID: b8f4cae72c15
Revises: 9282bfc18391
Create Date: 2019-03-28 16:22:12.971821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f4cae72c15'
down_revision = '9282bfc18391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('stay_type', sa.Enum('HOTEL', 'FRIENDS', 'CAMPING', 'HOUSE', name='staytype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'stay_type')
    # ### end Alembic commands ###
