"""empty message

Revision ID: c10cc917ed53
Revises: 67ada03db79b
Create Date: 2019-04-01 09:29:53.788998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c10cc917ed53'
down_revision = '67ada03db79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'geo_point', ['location_id'], ['id'])
    op.drop_column('media', 'file_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_info', mysql.VARCHAR(collation='utf8_bin', length=1000), nullable=True))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'location_id')
    # ### end Alembic commands ###
