"""empty message

Revision ID: cb0cc291dc83
Revises: 432585f064a8
Create Date: 2018-09-07 20:17:59.462187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0cc291dc83'
down_revision = '432585f064a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'content_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('content_html', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
