"""empty message

Revision ID: e1bc74cde696
Revises: 146495384f0a
Create Date: 2019-04-10 15:54:34.765943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1bc74cde696'
down_revision = '146495384f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyline_memebership',
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_contributor', sa.Boolean(), nullable=True),
    sa.Column('is_visitor', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('storyline_id', 'member_id')
    )
    op.drop_table('storyline_members')
    op.drop_constraint('storyline_ibfk_1', 'storyline', type_='foreignkey')
    op.drop_column('storyline', 'administrator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storyline', sa.Column('administrator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('storyline_ibfk_1', 'storyline', 'user', ['administrator_id'], ['id'])
    op.create_table('storyline_members',
    sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('storyline_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], name='storyline_members_ibfk_1'),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], name='storyline_members_ibfk_2'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('storyline_memebership')
    # ### end Alembic commands ###
