"""initial model

Revision ID: f6b11377d5cf
Revises: 
Create Date: 2018-08-30 18:02:28.036223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b11377d5cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('storyline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_timestamp'), 'story', ['timestamp'], unique=False)
    op.create_index(op.f('ix_story_title'), 'story', ['title'], unique=False)
    op.create_table('storyline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyline_name'), 'storyline', ['name'], unique=False)
    op.create_table('storyline_members',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('storyline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('current_line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_line_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('storyline_members')
    op.drop_index(op.f('ix_storyline_name'), table_name='storyline')
    op.drop_table('storyline')
    op.drop_index(op.f('ix_story_title'), table_name='story')
    op.drop_index(op.f('ix_story_timestamp'), table_name='story')
    op.drop_table('story')
    # ### end Alembic commands ###
