"""empty message

Revision ID: ffaed584810d
Revises: 591d18f794d0
Create Date: 2019-04-03 14:38:31.942802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffaed584810d'
down_revision = '591d18f794d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_date_for', table_name='story')
    op.create_index(op.f('ix_story_date_for'), 'story', ['date_for'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_date_for'), table_name='story')
    op.create_index('ix_story_date_for', 'story', ['date_for'], unique=False)
    # ### end Alembic commands ###
